// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: proto/vessel.proto

package vessel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vessel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight     int32                  `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId       string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vessel) Reset() {
	*x = Vessel{}
	mi := &file_proto_vessel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vessel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vessel) ProtoMessage() {}

func (x *Vessel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vessel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vessel.ProtoReflect.Descriptor instead.
func (*Vessel) Descriptor() ([]byte, []int) {
	return file_proto_vessel_proto_rawDescGZIP(), []int{0}
}

func (x *Vessel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vessel) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Vessel) GetMaxWeight() int32 {
	if x != nil {
		return x.MaxWeight
	}
	return 0
}

func (x *Vessel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vessel) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Vessel) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type Specification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int32                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight     int32                  `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specification) Reset() {
	*x = Specification{}
	mi := &file_proto_vessel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specification) ProtoMessage() {}

func (x *Specification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vessel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specification.ProtoReflect.Descriptor instead.
func (*Specification) Descriptor() ([]byte, []int) {
	return file_proto_vessel_proto_rawDescGZIP(), []int{1}
}

func (x *Specification) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Specification) GetMaxWeight() int32 {
	if x != nil {
		return x.MaxWeight
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vessel        *Vessel                `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels       []*Vessel              `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_vessel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vessel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_vessel_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetVessel() *Vessel {
	if x != nil {
		return x.Vessel
	}
	return nil
}

func (x *Response) GetVessels() []*Vessel {
	if x != nil {
		return x.Vessels
	}
	return nil
}

func (x *Response) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_proto_vessel_proto protoreflect.FileDescriptor

const file_proto_vessel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/vessel.proto\x12\x06vessel\"\xa0\x01\n" +
	"\x06Vessel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x1d\n" +
	"\n" +
	"max_weight\x18\x03 \x01(\x05R\tmaxWeight\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\"J\n" +
	"\rSpecification\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\x12\x1d\n" +
	"\n" +
	"max_weight\x18\x02 \x01(\x05R\tmaxWeight\"v\n" +
	"\bResponse\x12&\n" +
	"\x06vessel\x18\x01 \x01(\v2\x0e.vessel.VesselR\x06vessel\x12(\n" +
	"\avessels\x18\x02 \x03(\v2\x0e.vessel.VesselR\avessels\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated2y\n" +
	"\rVesselService\x12:\n" +
	"\rFindAvailable\x12\x15.vessel.Specification\x1a\x10.vessel.Response\"\x00\x12,\n" +
	"\x06Create\x12\x0e.vessel.Vessel\x1a\x10.vessel.Response\"\x00B\x10Z\x0e./proto;vesselb\x06proto3"

var (
	file_proto_vessel_proto_rawDescOnce sync.Once
	file_proto_vessel_proto_rawDescData []byte
)

func file_proto_vessel_proto_rawDescGZIP() []byte {
	file_proto_vessel_proto_rawDescOnce.Do(func() {
		file_proto_vessel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vessel_proto_rawDesc), len(file_proto_vessel_proto_rawDesc)))
	})
	return file_proto_vessel_proto_rawDescData
}

var file_proto_vessel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_vessel_proto_goTypes = []any{
	(*Vessel)(nil),        // 0: vessel.Vessel
	(*Specification)(nil), // 1: vessel.Specification
	(*Response)(nil),      // 2: vessel.Response
}
var file_proto_vessel_proto_depIdxs = []int32{
	0, // 0: vessel.Response.vessel:type_name -> vessel.Vessel
	0, // 1: vessel.Response.vessels:type_name -> vessel.Vessel
	1, // 2: vessel.VesselService.FindAvailable:input_type -> vessel.Specification
	0, // 3: vessel.VesselService.Create:input_type -> vessel.Vessel
	2, // 4: vessel.VesselService.FindAvailable:output_type -> vessel.Response
	2, // 5: vessel.VesselService.Create:output_type -> vessel.Response
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_vessel_proto_init() }
func file_proto_vessel_proto_init() {
	if File_proto_vessel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vessel_proto_rawDesc), len(file_proto_vessel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vessel_proto_goTypes,
		DependencyIndexes: file_proto_vessel_proto_depIdxs,
		MessageInfos:      file_proto_vessel_proto_msgTypes,
	}.Build()
	File_proto_vessel_proto = out.File
	file_proto_vessel_proto_goTypes = nil
	file_proto_vessel_proto_depIdxs = nil
}
